### ISSUE TITLE
Add support for ARM64

### ISSUE THREAD

**Issue by hiulit** [godotengine/buildroot#3]
Will it be possible?

Thanks!

**Comment by akien-mga** [comment]
Yes, that's something we want to do in our next toolchain update.

@Faless looked into it a few months ago - could you document your findings and/or WIP patches, so we make sure to do it right?

**Comment by Faless** [comment]
IIRC I had successfully built the toolchain for ARM64 using this branch: https://github.com/Faless/buildroot/commits/2022.02.x-fales

- I rebased the custom godot changes on the upstream buildroot `2022.02`.
- Updated the config files to the new buildroot version.
- Created a config file for arm64.
- Forced the glibc version to 2.28 for arm64 builds (previous versions are broken on arm64).

And that produced working linux buildroot as far as I remember.

Outstanding issues:
- Windows build are broken due to the `/lib` vs `/lib64` mess (some files are in `/lib` instead of `/lib64`, but only on arm64 builds).
- IIRC @hpvb  mentioned the removal of `BR2_PACKAGE_MESA3D_DRI_DRIVER_SWRAST` from upstream, resulted in my config including part of LLVM due to Gallium LLVMpipe, making the toolchain bigger.

**Comment by hiulit** [comment]
Any news on that?

**Comment by floriansimon1** [comment]
> IIRC I had successfully built the toolchain for ARM64 using this branch: https://github.com/Faless/buildroot/commits/2022.02.x-fales
> 
>     * I rebased the custom godot changes on the upstream buildroot `2022.02`.
> 
>     * Updated the config files to the new buildroot version.
> 
>     * Created a config file for arm64.
> 
>     * Forced the glibc version to 2.28 for arm64 builds (previous versions are broken on arm64).
> 
> 
> And that produced working linux buildroot as far as I remember.
> 
> Outstanding issues:
> 
>     * Windows build are broken due to the `/lib` vs `/lib64` mess (some files are in `/lib` instead of `/lib64`, but only on arm64 builds).
> 
>     * IIRC @hpvb  mentioned the removal of `BR2_PACKAGE_MESA3D_DRI_DRIVER_SWRAST` from upstream, resulted in my config including part of LLVM due to Gallium LLVMpipe, making the toolchain bigger.

I'm currently trying to build a toolchain, and it seems that there is a problem with make 4.4+ which ships with Arch these days. `make sdk` just hangs, and downgrading to `make` 4.3 seems to fix the issue.

See this [Stack Overflow post](https://stackoverflow.com/questions/76749559/why-does-make-hang-when-compiling-glibc) for details!

**Comment by floriansimon1** [comment]
For anyone else trying... I managed to build the export template for the Raspberry Pi 4 by lightly tweaking this: https://github.com/hiulit/cross-compile-godot-raspberry-pi/

However, the basic 3D example I compiled on my PC crashes after the Godot splash screen on the Pi, saying that Vulkan cannot create some buffer.

I think I'll just give up for now.

**Comment by hpvb** [comment]
Done
